package com.test.controller;

import java.security.Principal;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.security.authentication.AuthenticationManager;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.test.entity.User;
import com.test.entity.UserRequest;
import com.test.entity.UserResponse;
import com.test.jwtutil.JwtUtil;
import com.test.service.IUserService;

@RestController
public class UserRestController {
	
	@Autowired(required=true)
	private IUserService service;
	
	@Autowired(required=true)
	private JwtUtil jwtUtil;
	
	@Autowired(required=true)
	private AuthenticationManager authenticationManager;
	
	@PostMapping("/save")
	public ResponseEntity<String> saveuser(@RequestBody User user){
		
		Integer id=service.save(user);
		
		String body="user '"+id+"' saved";
		
		//return new ResponseEntity<String>(body,getStatus.ok);
		System.out.println("ll");
		return new ResponseEntity<>(body+"hello", HttpStatus.OK);
	}
	
	//2-validate user and generate token
	@PostMapping("/login")
	public ResponseEntity<UserResponse> loginUser(@RequestBody UserRequest request){
		//validate user name and password from database 
		authenticationManager.authenticate
		(new UsernamePasswordAuthenticationToken(
				request.getUsername(), request.getPassword()));
		
		String token=jwtUtil.generateToken(request.getUsername());
		
		return ResponseEntity.ok(new UserResponse(token,"success..! Generated by James"));
	}
	
	//after login 
	@PostMapping("/welcome")
	public ResponseEntity<String> accessData(Principal p){
		
		return ResponseEntity.ok("Hello User"+p.getName());
	}

}
